---
title: "Untitled"
author: "Sumitra"
date: "11/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#options(warn = -1)
#rm(list=ls())
library(data.table, warn.conflicts = FALSE, quietly = TRUE)
library(dplyr, warn.conflicts = FALSE, quietly = TRUE)
library(dtplyr, warn.conflicts = FALSE, quietly = TRUE)
library(ggplot2, warn.conflicts = FALSE, quietly = TRUE)
library(tidyr, warn.conflicts = FALSE, quietly = TRUE)
library(maps, warn.conflicts = FALSE, quietly = TRUE)

#df <- fread("../input/Indicators.csv")
df <- fread("~/Documents/EDA_2020/Datasets/Indicators.csv", header=TRUE)
df
```

# What can the World Development Indicator dataset tell us about unemployment?

# Where in the world are unemployment rates the highest?

```{r}
# Correction 

correction <- c("Antigua and Barbuda"="Antigua", "Bahamas, The"="Bahamas", "Brunei Darussalam"="Brunei", "Cabo Verde"="Cape Verde", "Congo, Dem. Rep."="Democratic Republic of the Congo", "Congo, Rep."="Republic of Congo", "Cote d'Ivoire"="Ivory Coast", "Egypt, Arab Rep."="Egypt", "Faeroe Islands"="Faroe Islands", "Gambia, The"="Gambia", "Iran, Islamic Rep."="Iran", "Korea, Dem. Rep."="North Korea", "Korea, Rep."="South Korea", "Kyrgyz Republic"="Kyrgyzstan", "Lao PDR"="Laos", "Macedonia, FYR"="Macedonia", "Micronesia, Fed. Sts."="Micronesia", "Russian Federation"="Russia", "Slovak Republic"="Slovakia", "St. Lucia"="Saint Lucia", "St. Martin (French part)"="Saint Martin", "St. Vincent and the Grenadines"="Saint Vincent", "Syrian Arab Republic"="Syria", "Trinidad and Tobago"="Trinidad", "United Kingdom"="UK", "United States"="USA", "Venezuela, RB"="Venezuela", "Virgin Islands (U.S.)"="Virgin Islands", "Yemen, Rep."="Yemen")

for (c in names((correction))) {
  df[df$CountryName==c,"CountryName"] = correction[c]
}

```


```{r}
ue2013 <-df %>%
         filter(Year==2014
         & IndicatorCode =="SL.UEM.TOTL.ZS")

map.world <- merge(map_data(map="world"),
                   dplyr::select(ue2013, CountryName, Value),
                   by.x='region',
                   by.y='CountryName',
                   all.x=TRUE,
                   fill=0)

map.world <- map.world[order(map.world$order),]

ggplot(map.world) +
  geom_map(map=map.world, aes(map_id=region, x=long, y=lat, fill=Value)) +
  borders("world",colour="black")+
  scale_fill_gradient(low ="yellow",high="red",guide="colourbar",name="Unemployment Rate (%)")+
  labs(title="Unemployment Rates (2013)",x="Longitude",y="Latitude")+
  theme(legend.position="bottom")
```


```{r}
ue2013 <-df %>%
         filter(Year==2014
         & IndicatorCode =="SL.UEM.TOTL.ZS")

map.world <- merge(map_data(map="world"),
                   dplyr::select(ue2013, CountryName, Value),
                   by.x='region',
                   by.y='CountryName',
                   all.x=TRUE,
                   fill=0)

map.world <- map.world[order(map.world$order),]

ggplot(map.world) +
  geom_map(map=map.world, aes(map_id=region, x=long, y=lat, fill=Value)) +
  borders("world",colour="black")+
  scale_fill_gradient(low ="#FFDB6D",high="#D16103",guide="colourbar",name="Unemployment Rate (%)")+
  labs(title="Unemployment Rates (2013)",x="Longitude",y="Latitude")+
  theme(legend.position="bottom")
```




