---
title: "World Development Indicators"
author: "Sumitra"
date: "11/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# libraries

```{r}
# install.packages("highcharter")
library(ggplot2)
library(dplyr)
library(highcharter)
library(plotly)
library(tidyverse)
```

# Download indicators.csv from kaggle
https://www.kaggle.com/worldbank/world-development-indicators


```{r}
data <- read.csv("~/Documents/EDA_2020/Datasets/Indicators.csv", header=TRUE)

```

# correction of country names

```{r}
correction <- c("Antigua and Barbuda"="Antigua", "Bahamas, The"="Bahamas", "Brunei Darussalam"="Brunei", 
                "Cabo Verde"="Cape Verde", "Congo, Dem. Rep."="Democratic Republic of the Congo", 
                "Congo, Rep."="Republic of Congo", "Cote d'Ivoire"="Ivory Coast", "Egypt, Arab Rep."="Egypt", 
                "Faeroe Islands"="Faroe Islands", "Gambia, The"="Gambia", "Iran, Islamic Rep."="Iran", 
                "Korea, Dem. Rep."="North Korea", "Korea, Rep."="South Korea", "Kyrgyz Republic"="Kyrgyzstan", 
                "Lao PDR"="Laos", "Macedonia, FYR"="Macedonia", "Micronesia, Fed. Sts."="Micronesia", 
                "Russian Federation"="Russia", "Slovak Republic"="Slovakia", "St. Lucia"="Saint Lucia", 
                "St. Martin (French part)"="Saint Martin", "St. Vincent and the Grenadines"="Saint Vincent", 
                "Syrian Arab Republic"="Syria", "Trinidad and Tobago"="Trinidad", "United Kingdom"="UK", 
                "United States"="United States of America", "Venezuela, RB"="Venezuela", 
                "Virgin Islands (U.S.)"="Virgin Islands", 
                "Yemen, Rep."="Yemen")


for (c in names((correction))) {
  data[data$CountryName==c,"CountryName"] = correction[c]
}
```

# indicators of interest

```{r}
# indicators of interest
ind <- c("SP.DYN.TFRT.IN", "SH.MED.BEDS.ZS", "SP.DYN.LE00.IN",
         "SP.POP.TOTL", "EN.ATM.CO2E.KT", "NY.GDP.PCAP.CD",
         "AG.YLD.CREL.KG", "TX.VAL.FOOD.ZS.UN","TX.VAL.FUEL.ZS.UN",
         "NY.GDP.MKTP.CN", "NY.GDP.PCAP.CD", "NY.GNP.MKTP.CD", "SL.UEM.TOTL.ZS")
```


```{r}
data1 <- data %>%
  filter(IndicatorCode %in% ind)
data1$CountryName <- as.factor(data1$CountryName)
countries <- c("France", "Germany", "United Kingdom",
               "United States of America", "India", "Pakistan", "China",
               "Arab World", "Russian Federation")
```


# background theme set


```{r}
thm <- hc_theme(colors = c('red', 'green', 'cyan', 'deeppink', 'yellow', 'indigo', 'blue'), 
                   chart = list(backgroundColor = "lightblue"), 
                   title = list(style = list(color = 'black',
                                             fontFamily = "Bold")), 
                   subtitle = list(style = list(color = 'black', 
                                                fontFamily = "Bold")), 
                   legend = list(itemStyle = list(fontFamily = 'Bold',
                                                  color = 'black'), 
                                 itemHoverStyle = list(color = 'white')))
```


# highcharts - JavaScript graphics library
https://www.htmlwidgets.org/showcase_highcharts.html


# population

```{r}
pop <- data1 %>%
  filter(IndicatorCode == "SP.POP.TOTL", 
         Year == 2014)

pop <- pop[-(1:33),]
hc_1 <- highchart() %>%
  hc_add_series_map(worldgeojson, pop, value = "Value", joinBy = c('name', "CountryName"))  %>% 
  hc_colorAxis(stops = color_stops(), max = 1364270000) %>% 
  hc_title(text = "Population") %>% 
  hc_subtitle(text = "2014") %>%
  hc_tooltip(borderWidth = 1.5, headerFormat = "") %>%
  hc_chart(zoomType = "xy") %>%
  hc_add_theme(thm)
```

```{r}
hc_1 
```


# unemployment


```{r}

unemp <- data1 %>%
  filter(IndicatorCode == "SL.UEM.TOTL.ZS", 
         Year == 2014)

unemp <- unemp[-(1:33),]
hc_2 <- highchart() %>%
  hc_add_series_map(worldgeojson, unemp, value = "Value", joinBy = c('name', "CountryName"))  %>% 
  hc_colorAxis(minColor = "yellow",maxColor= "red", max = 30) %>% 
  hc_title(text = "Unemployment") %>% 
  hc_subtitle(text = "2014") %>%
  hc_tooltip(borderWidth = 1.5, headerFormat = "") %>%
  hc_chart(zoomType = "xy") 
  
  

```

```{r}
hc_2
```


# Time Series Plots

```{r}
gdp_per_capita <- data %>%
  filter(IndicatorCode == "NY.GDP.PCAP.CD", CountryName %in% countries)

```

# background theme set

```{r}
thm2 <- hc_theme(colors = c('red', 'green', 'cyan', 'deeppink', 'yellow', 'indigo', 'blue'), 
                 chart = list(backgroundColor = "lightgrey"), 
                 title = list(style = list(color = 'black',
                                           fontFamily = "bold")), 
                 subtitle = list(style = list(color = 'black', 
                                              fontFamily = "bold")), 
                 legend = list(itemStyle = list(fontFamily = 'bold',
                                                color = 'black'), 
                               itemHoverStyle = list(color = 'white')))
```

# gdp

```{r}
hc_3 <- highchart() %>% 
  hc_add_series(gdp_per_capita, hcaes(x = Year, y = Value, group = CountryName), type = "line") %>%
  hc_tooltip(crosshairs = TRUE, borderWidth = 1.5, headerFormat = "", pointFormat = paste("Year: <b>{point.Year}</b> <br> GDP Per Capita:                           $<b>{point.Value}</b>  <br> CountryName: <b>{point.CountryName} <br>")) %>%
  hc_title(text = "GDP over the Years") %>% 
  hc_subtitle(text = "1960-2014") %>%
  hc_xAxis(title = list(text = "Year")) %>%
  hc_yAxis(title = list(text = "GDP in USD")) %>%
  hc_add_theme(thm2)
```


```{r}
hc_3
```




















